---
settings:
  name: ONTAP tools for VMware vSphere 9.12
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere-912"
    version-number: '9.12'
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere"
    version-number: '9.13'
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere-911"
    version-number: '9.11'
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere-910"
    version-number: '9.10'
  - name: ONTAP Tools für VMware vSphere
    url: "/ontap-tools-vmware-vsphere-98"
    version-number: '9.8'
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Dokumentation zu ONTAP Tools für VMware vSphere 9.12
    url: "/index.html"
  - title: Versionshinweise
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
